### ISSUE TITLE
Do we need hard-code /projects

### ISSUE THREAD

**Issue by dihuta** [whoGloo/nodespeed-ide#4]
Hi!
I specifiy my own projects folder but, it's seem open hard-code /projects?
Do we really need exactly '/projects' folder?

```
{ Error: ENOENT: no such file or directory, open '/projects/.meteor/local/dev_bundle/.node-gyp/4.8.3/include/node/openssl/archs/BSD-x86_64/opensslconf.h'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at getFileContentsForFile (/home/chronos/user/Downloads/nodespeed-ide/brackets-srv/search/node/FindInFilesDomain.js:217:41)
    at Immediate.fileCrawler (/home/chronos/user/Downloads/nodespeed-ide/brackets-srv/search/node/FindInFilesDomain.js:350:20)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
```

Thank you.

**Comment by asthomasdk** [comment]
I will need to look into that - we have always been using `/projects` in our containers. I cannot guarantee that there isn't a dependency somewhere on that path. 

You are welcome to go through the code and see if you can make it more generic - and submit a PR ;-)

**Comment by asthomasdk** [comment]
FYI - I have not tried using other project roots that `/projects` with nodespeed-ide - as we always have this defined as a directory for our Docker implementation. 

You are welcome to look at the code and see if you can make it more generic if needed.
